# -*- coding: utf-8 -*-
"""
Convert raw SSAA DPO preference pairs to LLaMA-Factory DPO JSONL.

Input: JSONL generated by build_ssaa_dpo_preference_pairs.py
Output default format (v1):
{
  "chosen_messages": [
    {"role": "system", "content": [{"type": "text", "value": "..."}], "loss_weight": 0.0},
    {"role": "user", "content": [{"type": "text", "value": "..."}], "loss_weight": 0.0},
    {"role": "assistant", "content": [{"type": "text", "value": "CONSTRAIN"}], "loss_weight": 1.0}
  ],
  "rejected_messages": [
    {"role": "system", "content": [{"type": "text", "value": "..."}], "loss_weight": 0.0},
    {"role": "user", "content": [{"type": "text", "value": "..."}], "loss_weight": 0.0},
    {"role": "assistant", "content": [{"type": "text", "value": "CHANGE"}], "loss_weight": 1.0}
  ]
}

Other supported formats:
{
  "messages": [
    {"role": "system", "content": "..."},
    {"role": "user", "content": "..."}
  ],
  "chosen": {"role": "assistant", "content": "CONSTRAIN"},
  "rejected": {"role": "assistant", "content": "CHANGE"}
}

Use --format openai or --format alpaca if your local LLaMA-Factory expects
those older/simple layouts.
"""

from __future__ import annotations

import argparse
import json
from pathlib import Path
from typing import Any, Dict, Iterable, Mapping

from dynamic_slot_memory import normalize_action


SYSTEM_TEXT = (
    "You are a slot-level semantic action classifier for Dialogue State Tracking. "
    "Predict exactly one semantic action label for the target slot in the current turn."
)

LABEL_DEFINITIONS = """[Label Definitions]
- NONE: The target slot is not activated in the current turn.
- CONSTRAIN: The current turn provides a concrete constraint or value for the target slot.
- CHANGE: The current turn changes the target slot from a previous concrete value to a different concrete value.
- DONTCARE: The current turn sets the target slot to an unconstrained preference.
- SWITCH: The current turn shifts to a new domain or task context and sets a constraint for the target slot.
- CONFIRM: The current turn confirms or accepts a value proposed by the system.
- REF-EXPLICIT: The current turn assigns or updates the target slot by explicitly referring to another slot as the source.
- REF-IMPLICIT: The current turn contains referring or elliptical behavior, but the source slot cannot be uniquely identified.
"""


def iter_jsonl(path: str) -> Iterable[Dict[str, Any]]:
    with open(path, "r", encoding="utf-8-sig") as f:
        for line in f:
            line = line.strip()
            if line:
                yield json.loads(line)


def write_jsonl(path: str, rows: Iterable[Mapping[str, Any]]) -> int:
    Path(path).parent.mkdir(parents=True, exist_ok=True)
    n = 0
    with open(path, "w", encoding="utf-8") as f:
        for row in rows:
            f.write(json.dumps(row, ensure_ascii=False) + "\n")
            n += 1
    return n


def get_desc(pair: Mapping[str, Any], key: str) -> str:
    desc = pair.get("slot_descriptions")
    if isinstance(desc, Mapping):
        return str(desc.get(key, "") or "None")
    return "None"


def get_context(pair: Mapping[str, Any], key: str) -> str:
    ctx = pair.get("dsm_context")
    if isinstance(ctx, Mapping):
        return str(ctx.get(key, "") or "None")
    return "None"


def build_user_prompt(pair: Mapping[str, Any], include_label_definitions: bool = True) -> str:
    parts = [
        "Instruction:",
        "Given the streamlined dialogue context constructed by Dynamic Slot Memory,",
        "one target slot, and the semantic descriptions of the target slot,",
        "predict only one semantic action label of the target slot in the current turn only.",
        "",
        "Output_Format:",
        "{CONSTRAIN}, {SWITCH}, {CHANGE}, {DONTCARE}, {CONFIRM}, {REF-EXPLICIT}, {REF-IMPLICIT}, {NONE}",
        "If and only if the predicted label is REF-EXPLICIT, an additional ref_slot may be included by downstream code.",
        "",
        "Decision Focus:",
        "- Do not treat a surface-level mention as a real slot activation.",
        "- Do not copy historical actions from memory unless the target slot is triggered again in the current turn.",
        "Priority Rules:",
        "REF-EXPLICIT > CONFIRM > REF-IMPLICIT ; NONE > DONTCARE > SWITCH > CHANGE > CONSTRAIN",
    ]

    if include_label_definitions:
        parts.extend(["", LABEL_DEFINITIONS.strip()])

    parts.extend([
        "",
        "Input:",
        "[Streamlined Dialogue Context]",
        "[1] Memory Turns for Target Slot",
        get_context(pair, "memory_turns"),
        "[2] Current Turn:",
        get_context(pair, "current_turn"),
        "[3] Domain Context:",
        get_context(pair, "domain_context"),
        "[4] Reference Slot Memory:",
        get_context(pair, "ref_slot_memory"),
        "[Target Slot]",
        str(pair.get("target_slot") or pair.get("slot") or ""),
        "[Slot Descriptions]",
        f"- Contrastive description: {get_desc(pair, 'contras_desc')}",
        f"- Type description: {get_desc(pair, 'type_desc')}",
        "",
        "[Answer]",
        "Output exactly one label token.",
    ])
    return "\n".join(parts)


def text_block(value: str) -> List[Dict[str, str]]:
    return [{"type": "text", "value": value}]


def v1_message(role: str, value: str, loss_weight: float) -> Dict[str, Any]:
    return {
        "role": role,
        "content": text_block(value),
        "loss_weight": loss_weight,
    }


def convert_pair(pair: Mapping[str, Any], out_format: str, include_label_definitions: bool) -> Dict[str, Any]:
    prompt = build_user_prompt(pair, include_label_definitions=include_label_definitions)
    chosen = normalize_action(pair.get("chosen"))
    rejected = normalize_action(pair.get("rejected"))

    meta = {
        "pair_type": pair.get("pair_type"),
        "dial_id": pair.get("dial_id"),
        "turn_id": pair.get("turn_id"),
        "slot": pair.get("slot"),
        "masked": pair.get("masked", False),
    }

    if out_format == "alpaca":
        return {
            "instruction": SYSTEM_TEXT,
            "input": prompt,
            "chosen": chosen,
            "rejected": rejected,
            **meta,
        }

    if out_format == "v1":
        return {
            "chosen_messages": [
                v1_message("system", SYSTEM_TEXT, 0.0),
                v1_message("user", prompt, 0.0),
                v1_message("assistant", chosen, 1.0),
            ],
            "rejected_messages": [
                v1_message("system", SYSTEM_TEXT, 0.0),
                v1_message("user", prompt, 0.0),
                v1_message("assistant", rejected, 1.0),
            ],
        }

    return {
        "messages": [
            {"role": "system", "content": SYSTEM_TEXT},
            {"role": "user", "content": prompt},
        ],
        "chosen": {"role": "assistant", "content": chosen},
        "rejected": {"role": "assistant", "content": rejected},
        **meta,
    }


def main() -> None:
    parser = argparse.ArgumentParser()
    parser.add_argument("--pair-path", required=True)
    parser.add_argument("--out-path", required=True)
    parser.add_argument("--format", choices=["v1", "openai", "alpaca"], default="v1")
    parser.add_argument("--no-label-definitions", action="store_true")
    args = parser.parse_args()

    rows = (
        convert_pair(
            pair,
            out_format=args.format,
            include_label_definitions=not args.no_label_definitions,
        )
        for pair in iter_jsonl(args.pair_path)
    )
    count = write_jsonl(args.out_path, rows)
    print(f"[DONE] wrote {count} LLaMA-Factory DPO samples -> {args.out_path}")


if __name__ == "__main__":
    main()
